services:
  - type: web
    name: backend de genai
    env: node
    region: oregon
    plan: standard
    buildCommand: cd server && npm install && npx puppeteer browsers install chrome --path /opt/render/.cache/puppeteer || true
    startCommand: npm start --prefix server
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PLATFORM_PATH
        value: ./platforms/agentetelecom
